backend:
  name: git-gateway
  repository: david8801/flow
  branch: master

local_backend: true

media_folder: public/img
public_folder: img

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Article"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Category", name: "category", widget: relation, collection: "categories", displayFields: [ "name" ], searchFields: [ "name" ], valueField: "name" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Sponsored", name: "sponsored", widget: "boolean", default: false }
      - { label: "Trending", name: "trending", widget: "boolean", default: false }
      - { label: "Author", name: "author", widget: relation, collection: "authors", displayFields: [ "name" ], searchFields: [ "name" ], valueField: "name" }
      - label: 'Tags'
        name: "tags"
        widget: list
        fields:
          - label: "Name"
            name: "name"
            widget: relation
            collection: "tags"
            displayFields: [ "name" ]
            searchFields: [ "name" ]
            valueField: "name"

  - name: "categories"
    label: "Categories"
    label_singular: "Category"
    folder: "content/categories"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Color", name: "color", widget: "color"}
      - {label: "Order", name: "order", widget: "number"}

  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    folder: "content/tags"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Name", name: "name", widget: "string"}

  - name: "authors"
    label: "Authors"
    label_singular: "Author"
    folder: "content/authors"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Name", name: "name", widget: "string"}

  - name: "settings"
    label: "Settings"
    files:
      - label: "Running Line"
        name: "running_line"
        file: "content/running_line.yml"
        fields:
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Active", name: "active", widget: "boolean"}
