backend:
  name: git-gateway
  repository: david8801/flow
  branch: master

local_backend: true

media_folder: public/img
public_folder: img

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Article"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Category", name: "category", widget: 'select', options: [ 'home', 'it', 'tech', 'startups', 'blockchain', 'design', 'games' ] }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Author", name: "author", widget: relation, collection: "authors", displayFields: [ "name" ], searchFields: [ "name" ], valueField: "name" }
      - label: 'Tags'
        name: "tags"
        widget: list
        fields:
          - label: "Name"
            name: "name"
            widget: relation
            collection: "tags"
            displayFields: [ "name" ]
            searchFields: [ "name" ]
            valueField: "name"

  - name: "tags"
    label: "Tags"
    label_singular: "Tag"
    folder: "content/tags"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Name", name: "name", widget: "string"}

  - name: "authors"
    label: "Authors"
    label_singular: "Author"
    folder: "content/authors"
    create: true
    identifier_field: "name"
    fields:
      - {label: "Name", name: "name", widget: "string"}